networks:
  fut-app:
    driver: bridge

services:
  postgres:
    networks:
      - fut-app
    image: "postgres:14.3-alpine"
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: futapp
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"
    
  omnidb:
    networks:
      - fut-app
    image: "taivokasper/omnidb"
    ports:
      - "8090:8080"

  app:
    build:
      context: ..
      dockerfile: dockerfile
    networks:
      - fut-app
    environment:
      APP_HOST: "0.0.0.0"
      APP_PORT: "8080"
      APP_NAME: "fut-app"
      PG_HOST: "postgres"
      PG_PORT: "5432"
      PG_USER: "postgres"
      PG_PASSWORD: "123456"
      PG_NAME: "fut-app"
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped